#!/bin/ash

. /usr/share/libubox/jshn.sh

hosts=$(ubus call luci-rpc getHostHints)
macs1=$(ubus call iwinfo assoclist '{"device": "wlan0"}')
macs2=$(ubus call iwinfo assoclist '{"device": "wlan1"}')

macs1=$(echo $macs1 | grep -Eo "([A-Z0-9]{2}:){5}[A-Z0-9]{2}")
macs2=$(echo $macs2 | grep -Eo "([A-Z0-9]{2}:){5}[A-Z0-9]{2}")

macs=$(echo $macs1 $macs2)

json_init

json_load "$hosts"

for i in $macs; do
	json_select $i
	json_get_var name name
	json_close_object
	echo $name
done
